name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: "runnable_ci"
  TURBO_RUN_SUMMARY: true

jobs:
  lint:
    name: ⬣ Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.20.0
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

  build_and_test:
    name: 🏗 Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.20.0
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔨 Build
        run: pnpm build

      - name: ʦ Typecheck
        run: pnpm typecheck

      - name: 🧪 Test
        run: pnpm test
